### PR TITLE
Added Algerian localization

### PR DESCRIPTION
**Pull request by noureddineme**

### CODE REVIEW

**Comment by nelefth** [comment]
Hi @noureddineme . Thank you for your contribution.

**Comment by noureddineme** [comment]
hmmm I see @nelefth, Thank you for your reply.
Looking forward to have new information.

**Comment by nelefth** [comment]
@noureddineme we have just added the new language to our list. You can find it in Transifex.

**Comment by noureddineme** [comment]
Thank you @nelefth, yes i can find it in the languages list, but when trying in user setting I can't find it, also when I try to request new languages for some projects I can't find it too.

screenshot from 2016-08-18 09-35-25

**Pull request closed without merging**
